# Generated by Django 4.2.3 on 2023-10-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='breakfast_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='dinner_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='lunch_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
